/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_chat_pb from '../proto/chat_pb';


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.ChatMessage,
    proto_chat_pb.ChatResponse,
    (request: proto_chat_pb.ChatMessage) => {
      return request.serializeBinary();
    },
    proto_chat_pb.ChatResponse.deserializeBinary
  );

  sendMessage(
    request: proto_chat_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.ChatResponse>;

  sendMessage(
    request: proto_chat_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.ChatResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.ChatResponse>;

  sendMessage(
    request: proto_chat_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.ChatResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorGetMessagesStream = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/GetMessagesStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.ChatMessage,
    proto_chat_pb.ChatMessage,
    (request: proto_chat_pb.ChatMessage) => {
      return request.serializeBinary();
    },
    proto_chat_pb.ChatMessage.deserializeBinary
  );

  getMessagesStream(
    request: proto_chat_pb.ChatMessage,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.ChatMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat.ChatService/GetMessagesStream',
      request,
      metadata || {},
      this.methodDescriptorGetMessagesStream);
  }

}

